<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
      <title>Ovlii's Password Generator</title>
      <link rel="stylesheet" type="text/css" href="view.css" media="all"/>
      <script type="text/javascript" src="view.js"></script>
       <?php require('functions.php'); ?>
   </head>
   <body id="main_body" >
      <div id="form_container">
         <h1><a>Ovlii's Password Generator</a></h1>
         <form class="appnitro"  method="post" 
            action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
            <div class="form_description">
               <h2>Ovlii's - Password Generator</h2>
               <p>Secure Password generator </p>
            </div>
            <ul >
               <li>
                  <label class="description">Generated Password is  </label>
                  <div class="password">
		  <p>
                     <?php echo generate_password(); ?>
		  </p>
                  </div>
               </li>
               <li>
                  <label class="description">Select number of words ( Default 3)  </label>
		<div>
		<select class="element select small" id="no_of_words" name="no_of_words"> 
			<option value="1" >1</option>
			<option value="2" >2</option>
			<option value="3" selected="selected" >3</option>
			<option value="4" >4</option>
			<option value="5" >5</option>
			<option value="6" >6</option>
			<option value="7" >7</option>
			<option value="8" >8</option>
			<option value="9" >9</option>

		</select>
		</div> 
			  <p class="guidelines"><small>Please select the number of words ( Maximum 9)</small></p>
               </li>
               <li>
                  <span>
                  <input id="add_number" name="add_number" class="element checkbox" type="checkbox" value="1" />
                  <label class="choice">Add a random Number (0-9)</label>
                  </span>
                  <p class="guidelines"><small>Please select this if you want a random number to be added at the end.</small></p>
               </li>
               <li>
                  <span>
                  <input id="add_special" name="add_special" class="element checkbox" type="checkbox" value="1" />
                  <label class="choice">Add special characters</label>
                  </span>
                  <p class="guidelines"><small>Add a special characters at the end of the password.</small></p>
               </li>
               <li>
                  <label class="description">Select a seperator ( eg. $, !, ~ etc. Deault is -) </label>
                  <div>
                     <input id="add_seperator" name="add_seperator" class="element text small" type="text" maxlength="1" value=""/> 
                  </div>
                  <p class="guidelines"><small>Please select the separator to be used between the words for the password.</small></p>
               </li>
               <li>
                  <label class="description">First Upper/All Upper </label>
                  <span>
                  <input id="make_upper" name="make_upper" class="element radio" type="radio" value="0" />
                  <label class="choice">First Letter Upper</label>
                  <input id="make_upper" name="make_upper" class="element radio" type="radio" value="1" />
                  <label class="choice">All Word Upper</label>
                  </span>
                  <p class="guidelines"><small>Select if First letter of word upper or all the word to be upper.</small></p>
               </li>
               <li class="buttons">
                  <input id="saveForm" class="button_text" type="submit" name="submit" value="Generate Password!" />
               </li>
            </ul>
         </form>
         <p class='details'>
			<a href='http://xkcd.com/936/'>xkcd password strength</a><br/>
		
			<a href='http://xkcd.com/936/'>
				<img class='comic' src='http://imgs.xkcd.com/comics/password_strength.png' alt='xkcd style passwords'/>
			</a>
			<br/>
		</p>
         <div id="footer">
            Generated by <a href="http://www.phpform.org">pForm</a>
         </div>
      </div>
   </body>
</html>
